name: Deploy to Hostinger

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: SFTP Deploy to Hostinger
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: '92.112.189.250'
          port: '65002'
          username: 'u384342620'
          password: '${{ secrets.FTP_PASSWORD }}'
          local_path: './out/'
          remote_path: 'public_html'
          args: '-avzr --delete'
          include: '*'
          exclude: 'node_modules'
