name: Deploy to Hostinger

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: SFTP Deploy to Hostinger
        uses: easingthemes/ssh-deploy@v4
        with:
          SOURCE: "./out/"
          REMOTE_HOST: "92.112.189.250"
          REMOTE_PORT: "65002"
          REMOTE_USER: "u384342620"
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_PATH: "/public_html/"
          ARGS: "-rltgoDzvO"
          EXCLUDE: "/node_modules/"
